version: '3.9'
name: basic_db

services:
  postgres_db:
    image: postgres

    environment:
      POSTGRES_PASSWORD: qwerty

    volumes:
      - ./dumps:/dumps
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    restart: always

  mysql_db:
    image: mysql

    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: qwerty

    volumes:
      - ./dumps:/dumps
      - mysql_data:/var/lib/mysql

    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql_data:
  postgres_data: